In [1]:
from transformers import pipeline

translator = pipeline("translation_en_to_fr")
result = translator("I love deep learning.")
print(result)


d:\Learning\lenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
d:\Learning\lenv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ravia\.cache\huggingface\hub\models--google-t5--t5-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/hugging

[{'translation_text': "J'aime l'apprentissage approfondi."}]


In [3]:
import numpy as np

# Scalar
a = np.array(5)             # 0D
# Vector
b = np.array([1, 2, 3])     # 1D
# Matrix
c = np.array([[1, 2], [3, 4]])  # 2D
# 3D tensor
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [5]:
print(a,b,c,d )

5 [1 2 3] [[1 2]
 [3 4]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x + y)  # Element-wise addition
print(x - y)  # Element-wise subtraction

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [7]:
print(x * y)


[[ 5 12]
 [21 32]]


In [8]:
print(np.dot(x, y))  # Matrix multiplication


[[19 22]
 [43 50]]


In [9]:
z = np.array([1, 2, 3, 4, 5, 6])
z = z.reshape((2, 3))  # Convert 1D to 2D
print(z)

[[1 2 3]
 [4 5 6]]


In [10]:
print(x.T)  # Flip rows and columns


[[1 3]
 [2 4]]


In [11]:
print(x.sum())      # Sum of all elements
print(x.mean())     # Average
print(x.max())      # Max value


10
2.5
4


In [12]:
print(x.shape)      # (2, 2)
print(x.ndim)       # 2 (2D)


(2, 2)
2


In [13]:
import torch

# 1D tensor
a = torch.tensor([1.0, 2.0, 3.0])

# 2D tensor
b = torch.tensor([[1, 2], [3, 4]])


In [14]:
print(a)
print(b)

tensor([1., 2., 3.])
tensor([[1, 2],
        [3, 4]])


In [15]:
# Add
c = a + a

# Multiply
d = b * 2

# Matrix multiply
e = torch.matmul(b, b)


In [16]:
import torch
import torch.nn as nn

rnn = nn.RNN(input_size=10, hidden_size=20, num_layers=1)

# (sequence_len, batch_size, input_size)
x = torch.randn(5, 1, 10)
h0 = torch.zeros(1, 1, 20)  # initial hidden state

output, hn = rnn(x, h0)

print(output.shape)  # Output at each time step
print(hn.shape)      # Final hidden state


torch.Size([5, 1, 20])
torch.Size([1, 1, 20])


In [17]:
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, 3)  # 1 input channel (grayscale), 16 filters
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(16 * 13 * 13, 10)  # for 28x28 image

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = x.view(-1, 16 * 13 * 13)
        x = self.fc1(x)
        return x


In [3]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode(sentences)
print(embeddings)

[[ 6.76568821e-02  6.34959117e-02  4.87131439e-02  7.93049559e-02
   3.74480635e-02  2.65279901e-03  3.93749736e-02 -7.09847594e-03
   5.93614466e-02  3.15370448e-02  6.00980595e-02 -5.29052205e-02
   4.06067669e-02 -2.59308070e-02  2.98428256e-02  1.12692453e-03
   7.35148787e-02 -5.03818952e-02 -1.22386634e-01  2.37028133e-02
   2.97265332e-02  4.24768552e-02  2.56337691e-02  1.99518725e-03
  -5.69191128e-02 -2.71598194e-02 -3.29035521e-02  6.60248771e-02
   1.19007163e-01 -4.58791517e-02 -7.26214498e-02 -3.25840227e-02
   5.23413569e-02  4.50553037e-02  8.25298857e-03  3.67024094e-02
  -1.39415646e-02  6.53918535e-02 -2.64272671e-02  2.06397686e-04
  -1.36643434e-02 -3.62810977e-02 -1.95043795e-02 -2.89738216e-02
   3.94270122e-02 -8.84090662e-02  2.62427074e-03  1.36713488e-02
   4.83062565e-02 -3.11566107e-02 -1.17329188e-01 -5.11690341e-02
  -8.85288268e-02 -2.18962803e-02  1.42986607e-02  4.44167592e-02
  -1.34814996e-02  7.43392557e-02  2.66383160e-02 -1.98762398e-02
   1.79191

In [9]:

# Use a pipeline as a high-level helper
from PIL import Image
from transformers import pipeline

img = Image.open(r"C:\Users\ravia\OneDrive\Pictures\lord-krishna-5120x2880-18377.jpg")
classifier = pipeline("image-classification", model="Falconsai/nsfw_image_detection")
classifier(img)


Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Device set to use cpu


[{'label': 'normal', 'score': 0.9998260140419006},
 {'label': 'nsfw', 'score': 0.00017402302182745188}]

In [8]:

# Load model directly
import torch
from PIL import Image
from transformers import AutoModelForImageClassification, ViTImageProcessor

img = Image.open(r'C:\Users\ravia\OneDrive\Pictures\lord-krishna-5120x2880-18377.jpg')
model = AutoModelForImageClassification.from_pretrained("Falconsai/nsfw_image_detection")
processor = ViTImageProcessor.from_pretrained('Falconsai/nsfw_image_detection')
with torch.no_grad():
    inputs = processor(images=img, return_tensors="pt")
    outputs = model(**inputs)
    logits = outputs.logits

predicted_label = logits.argmax(-1).item()
model.config.id2label[predicted_label]


d:\Learning\lenv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ravia\.cache\huggingface\hub\models--Falconsai--nsfw_image_detection. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


'normal'